---
title: "Simulation codes"
author: "Kosuke Inoue"
date: "2024-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = structure(c(CRAN = "http://cran.rstudio.com/")))
```

```{r, include=FALSE}
##This is example codes for HTE assessment using machine learning algorithms.
##MS Title: Machine Learning Approaches to Evaluate Heterogeneous Treatment Effects in Randomized Controlled Trials: A Scoping Review.
##Lasso, Causal forest, Bayesian causal forest codes are created based on from their vignette
##Meta-learner R codes are shown based on codes in: Salditt M, et al. A Tutorial Introduction to Heterogeneous Treatment Effect Estimation with Meta-learners.(Adm Policy Ment Health. doi:10.1007/s10488-023-01303-9)

##The codes have the following steps
###Step 1: Install packages
###Step 2: Set parameters and data generation
###Step 3: Creating datasets
###Step 4: Run analysis (Lasso, Causal forest, Bayesian Causal forest)
###Step 5: Run analysis (Meta-learner)
###Step 6: Evaluation of the model performance (example code for calibration)
```

```{r}
###Step 0: Basic information
Sys.time()
# Get detailed R session and system information
session_info <- sessionInfo()
system_info <- Sys.info()
# Combine the output
list(session_info = session_info, system_info = system_info)
```

```{r, include=FALSE}
###Step 1: Install packages
list.of.packages <- c( "dplyr","Hmisc", "FindIt", "dbarts", "grf", "rlearner", "tidyverse", "bcf", "ranger", 
                       "BART", "tidytreatment", "dplyr", "tidybayes", "ggplot2", "lmtest", "sandwich", "gridExtra")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, library, character.only = TRUE)
#library(devtools) 
#install_github("xnie/rlearner")
#library(rlearner)
```

```{r}
###Step 2: Set parameters and data generation
N<-10000
setseed<-123
nthread<-8

set.seed(setseed)
T=rbinom(N, 1, 0.5)
age=rnorm(N, 60, 10)
sbp=rnorm(N, 120, 15)
eGFR=rnorm(N, 60, 20)
eGFR <- pmin(pmax(eGFR, 10), 120)
statin=rbinom(N, 1, 0.43)

#scenario 1: linear relationship
beta1<-(0.05+0.06*statin+0.002*eGFR)
regY1<- 0.20+beta1*T+0.001*(eGFR-60)+0.05*statin+0.001*(age-60)+0.001*(sbp-120)
summary(regY1)
regY1 <- pmin(pmax(regY1, 0), 1)
Y1<- rbinom(N, 1, regY1)

#scenario 2: non-linear relationship
initial_beta2<-(0.05)
beta2 <- ifelse(eGFR < 45, initial_beta2 * (1+(45 - 60)/20)+0.1*statin,
                ifelse(eGFR >= 45 & eGFR < 90, initial_beta2 * (1+(eGFR - 60)/20)+0.1*statin,
                       initial_beta2 * (1+(90 - 60)/20)+0.1*statin))
regY2<- 0.20+beta2*T+0.001*(eGFR-60)+0.05*statin+0.001*(age-60)+0.001*(sbp-120)
summary(regY2)
regY2 <- pmin(pmax(regY2, 0), 1)
Y2<- rbinom(N, 1, regY2)
```

```{r}
###Step 3: Creating datasets
#scenario 1 (binary)
Y<-Y1  
data_1<- data.frame(age,  sbp,  eGFR, statin, T, Y)
#scenario 2 (binary)
Y<-Y2  
data_2<- data.frame(age,  sbp,  eGFR, statin, T, Y)
#scenario 1' (continuous)
Y<-regY1  
data_3<- data.frame(age,  sbp,  eGFR, statin, T, Y)
#scenario 2' (continuous)
Y<-regY2  
data_4<- data.frame(age,  sbp,  eGFR, statin, T, Y)
```

```{r}
###Step 4: Run analysis (Lasso, Causal forest, Bayesian Causal forest)
run_step4 <- function(dat0, suffix) {
  
##Ensure output directory exists
output_dir <- file.path("output", paste0("data", suffix))

##4-1. Lasso
set.seed(setseed)
dat1<-dat0
model_lasso <-FindIt(model.treat= Y ~ T, model.main= ~ age + sbp + eGFR + statin,
                     model.int= ~ age + sbp + eGFR + statin, 
                     data = dat1, type="binary", treat.type="single", fit.glmnet=TRUE) 

pred_lasso <- predict(model_lasso)
dat1_lasso=as.data.frame(pred_lasso$data)
dat1_lasso <- dat1_lasso[order(as.numeric(row.names(dat1_lasso))), ]
hte_lasso <- dat1_lasso$Treatment.effect

dat1$CATE<-hte_lasso
 #Create the plot
dat1$statin <- factor(dat1$statin)
fig_lasso<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  # Add points
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) +  # Set custom colors
  theme_minimal() +  # Minimal theme
  labs(x = "eGFR", y = "CATE", title = "")  # Add labels and title
ggsave(filename = file.path(output_dir, paste0("fig_lasso_", suffix, ".png")), plot = fig_lasso)

##4-2. Causal forest 
dat1<-dat0
dat1 <- dat1 %>%
  mutate_at(vars(statin), ~ as.numeric(as.character(.)))
Y <-  (dat1$Y)
W <-  (dat1$T)
X0 <-  subset(dat1, select=-Y)
X1 <-  subset(X0, select=-T)
model_grf <- causal_forest(X1, Y, W, 
                           honesty = TRUE, 
                           tune.parameters="all",
                           seed = setseed,
                           num.threads = nthread)
hte_grf <- predict(model_grf)$predictions

dat1$CATE<-hte_grf
 #Create the plot
dat1$statin <- factor(dat1$statin)
fig_grf<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  # Add points
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) +  # Set custom colors
  theme_minimal() +  # Minimal theme
  labs(x = "eGFR", y = "CATE", title = "")  # Add labels and title
ggsave(filename = file.path(output_dir, paste0("fig_grf_", suffix, ".png")), fig_grf)

##4-3. Bayesian Causal Forest
dat1<-dat0
dat1 <- dat1 %>%
mutate_at(vars(statin), ~ as.numeric(as.character(.)))
Y <-  (dat1$Y)
W <-  (dat1$T)
X0 <-  subset(dat1, select=-Y)
X1 <-  subset(X0, select=-T)
X2 <- as.matrix(X1)
model <- glm(W ~ age + sbp + eGFR + statin, family = binomial)
pi <- predict(model, type = "response")

model_bcf <- bcf(y             = Y,
              z                = W,
              x_control        = X2,
              x_moderate       = X2,
              pihat            = pi,
              nburn            = 100, # nburn should be much larger, at least a few thousand
              nsim             = 10,  # nsim should be much larger, at least a few thousand
              save_tree_directory = 'log',
              log_file = file.path("log", sprintf("bcf_log_%s.txt", format(Sys.time(), "%Y%m%d_%H%M%S"))),
              random_seed = setseed,
              n_threads = nthread)

dat1$CATE<-colMeans(model_bcf$tau)

 #Create the plot
dat1$statin <- factor(dat1$statin)
fig_bcf<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  # Add points
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) +  # Set custom colors
  theme_minimal() +  # Minimal theme
  labs(x = "eGFR", y = "CATE", title = "")  # Add labels and title
ggsave(filename = file.path(output_dir, paste0("fig_bcf_", suffix, ".png")), fig_bcf)

library(gridExtra)
fit_all<- grid.arrange(fig_lasso+ ggtitle('Lasso'), 
                      fig_grf+ ggtitle('Causal forest'), 
                      fig_bcf+ ggtitle('Bayesian causal forest'),
                      ncol=2)
ggsave(filename = file.path(output_dir, paste0("fig_all_", suffix, ".png")), fit_all)

return(list(Lasso = fig_lasso))
return(list(GRF = fig_grf))
return(list(BCF = fig_bcf))
return(list(All = fit_all))
}

#Run the function for each dataset
dataset_names <- c("data_1", "data_2", "data_3", "data_4")
plots_list <- list()  # Initialize an empty list to store plots

#Loop through dataset names and call the analysis function
for (dataset_name in dataset_names) {
  #Retrieve the dataset
  dataset <- get(dataset_name)
  #Extract the numeric suffix
  suffix <- gsub("data_", "", dataset_name)
  #Call the analysis function
  plots <- run_step4(dataset, suffix)
  #Assign each plot a name with the suffix and store in the list
  for (plot_name in names(plots)) {
    full_plot_name <- paste(plot_name, suffix, sep = "_")
    plots_list[[full_plot_name]] <- plots[[plot_name]]
  }
}
```

```{r}
###Step 5: Run analysis (Meta-learner)
covariates<-c("age", "sbp", "eGFR", "statin")
run_step5 <- function(dat0, suffix) {
output_dir <- file.path("output", paste0("data", suffix))

##5-1. S-learner
dat1<-dat0
mu_fit <- ranger(y = dat1$Y, x = dat1[, c("T", covariates)], keep.inbag = TRUE, seed = setseed, num.threads =nthread)

#Predict mu_0 
dat1TMP <- dat1
dat1TMP$T <- 0
mu0_hat_s <- rep(0, nrow(dat1))
mu0_hat_s[dat1$T == 0] <- mu_fit$predictions[dat1$T == 0]
mu0_hat_s[dat1$T == 1] <- predict(mu_fit, dat1TMP)$predictions[dat1$T == 1]

#Predict mu_1 
dat1TMP$T <- 1
mu1_hat_s <- rep(0,  nrow(dat1))
mu1_hat_s[dat1$T == 1] <- mu_fit$predictions[dat1$T == 1]
mu1_hat_s[dat1$T == 0] <- predict(mu_fit, dat1TMP)$predictions[dat1$T == 0]

cate_s <- mu1_hat_s - mu0_hat_s
dat1$CATE<-cate_s
dat1$statin <- factor(dat1$statin)
 #Create the plot
fig_Sranger<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) +  
  theme_minimal() + 
  labs(x = "eGFR", y = "CATE", title = "")  
ggsave(filename = file.path(output_dir, paste0("fig_Sranger_", suffix, ".png")), fig_Sranger)

##5-2. T-learner
dat1<-dat0
# Create separate data frames for the control and the treatment group
dat1_0 <- dat1[dat1$T == 0, ]
dat1_1 <- dat1[dat1$T == 1, ]

#Predict mu_0 
mu0_fit <- ranger(y = dat1_0$Y, x = dat1_0[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
mu0_hat <- rep(0, nrow(dat1))
mu0_hat[dat1$T == 0] <- mu0_fit$predictions
mu0_hat[dat1$T == 1] <- predict(mu0_fit, dat1_1)$predictions

#Predict mu_1
mu1_fit <- ranger(y = dat1_1$Y, x = dat1_1[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
mu1_hat <- rep(0, nrow(dat1))
mu1_hat[dat1$T == 1] <- mu1_fit$predictions 
mu1_hat[dat1$T == 0] <- predict(mu1_fit, dat1_0)$predictions

# Compute CATE
cate_t <- mu1_hat - mu0_hat
dat1$CATE<-cate_t
dat1$statin <- factor(dat1$statin)
 #Create the plot
fig_Tranger<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) +  
  theme_minimal() +  
  labs(x = "eGFR", y = "CATE", title = "") 
ggsave(filename = file.path(output_dir, paste0("fig_Tranger_", suffix, ".png")), fig_Tranger)


##5-3. X-learner 
dat1<-dat0
# Create separate data frames for the control and the treatment group
dat1_0 <- dat1[dat1$T == 0, ]
dat1_1 <- dat1[dat1$T == 1, ]

#Predict mu_0
mu0_fit <- ranger(y = dat1_0$Y, x = dat1_0[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
mu0_hat <- rep(0, nrow(dat1))
mu0_hat[dat1$T == 0] <- mu0_fit$predictions 
mu0_hat[dat1$T == 1] <- predict(mu0_fit, dat1_1)$predictions

#Predict mu_1
mu1_fit <- ranger(y = dat1_1$Y, x = dat1_1[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
mu1_hat <- rep(0, nrow(dat1))
mu1_hat[dat1$T == 1] <- mu1_fit$predictions 
mu1_hat[dat1$T == 0] <- predict(mu1_fit, dat1_0)$predictions

#Compute the pseudo-outcome using the estimated conditional mean function 
psi_x_0 <- predict(mu1_fit, dat1_0)$predictions - dat1_0$Y
psi_x_1 <- dat1_1$Y - predict(mu0_fit, dat1_1)$predictions

#Fit random forest using the pseudo-outcome and the covariates separately in the two groups
tau_x_0_fit <- ranger(y = psi_x_0, x = dat1_0[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
tau_x_1_fit <- ranger(y = psi_x_1, x = dat1_1[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)

#Predict treatment effects per group 
tau_x_0_hat <- rep(0, nrow(dat1))
tau_x_0_hat[T == 0] <- tau_x_0_fit$predictions
tau_x_0_hat[T == 1] <- predict(tau_x_0_fit, dat1_1)$predictions
tau_x_1_hat <- rep(0, nrow(dat1))
tau_x_1_hat[T == 1] <- tau_x_1_fit$predictions
tau_x_1_hat[T == 0] <- predict(tau_x_1_fit, dat1_0)$predictions

#Estimate the propensity score
ps_fit <- ranger(y = dat1$T, x = dat1[, covariates], probability = TRUE)
ps_hat <- ps_fit$predictions[,2] 

#Ensure positivity 
epsilon <- .01
ps_hat <- ifelse(ps_hat < epsilon, epsilon, ifelse(ps_hat > 1 - epsilon, 1 - epsilon, ps_hat))

#Compute the CATE as propensity score-weighted combination of the group-specific estimates
cate_x <- ps_hat * tau_x_0_hat + (1 - ps_hat) * tau_x_1_hat
dat1$CATE<-cate_x
dat1$statin <- factor(dat1$statin)
 #Create the plot
fig_Xranger<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) + 
  theme_minimal() +  
  labs(x = "eGFR", y = "CATE", title = "")  
ggsave(filename = file.path(output_dir, paste0("fig_Xranger_", suffix, ".png")), fig_Xranger)

##5-4. DR-learner
dat1<-dat0
# Create separate data frames for the control and the treatment group:
dat1_0 <- dat1[dat1$T == 0, ]
dat1_1 <- dat1[dat1$T == 1, ]

#Predict mu_0
mu0_fit <- ranger(y = dat1_0$Y, x = dat1_0[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
mu0_hat <- rep(0, nrow(dat1))
mu0_hat[dat1$T == 0] <- mu0_fit$predictions 
mu0_hat[dat1$T == 1] <- predict(mu0_fit, dat1_1)$predictions

#Predict mu_1
mu1_fit <- ranger(y = dat1_1$Y, x = dat1_1[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
mu1_hat <- rep(0, nrow(dat1))
mu1_hat[dat1$T == 1] <- mu1_fit$predictions 
mu1_hat[dat1$T == 0] <- predict(mu1_fit, dat1_0)$predictions

#Compute the pseudo-outcome using the estimated conditional mean function 
psi_x_0 <- predict(mu1_fit, dat1_0)$predictions - dat1_0$Y
psi_x_1 <- dat1_1$Y - predict(mu0_fit, dat1_1)$predictions

#Fit random forest using the pseudo-outcome and the covariates separately in the two groups
tau_x_0_fit <- ranger(y = psi_x_0, x = dat1_0[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
tau_x_1_fit <- ranger(y = psi_x_1, x = dat1_1[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)

#Predict treatment effects per group using the two resulting models
tau_x_0_hat <- rep(0, nrow(dat1))
tau_x_0_hat[T == 0] <- tau_x_0_fit$predictions
tau_x_0_hat[T == 1] <- predict(tau_x_0_fit, dat1_1)$predictions
tau_x_1_hat <- rep(0, nrow(dat1))
tau_x_1_hat[T == 1] <- tau_x_1_fit$predictions
tau_x_1_hat[T == 0] <- predict(tau_x_1_fit, dat1_0)$predictions

#Estimate the propensity score
ps_fit <- ranger(y = dat1$T, x = dat1[, covariates], probability = TRUE, seed = setseed, num.threads =nthread)
ps_hat <- ps_fit$predictions[,2] 

#Ensure positivity
epsilon <- .01
ps_hat <- ifelse(ps_hat < epsilon, epsilon, ifelse(ps_hat > 1 - epsilon, 1 - epsilon, ps_hat))

#Compute the pseudo-outcome of the DR-learner
augmentedTerm <- 1/ps_hat * (dat1$T * (dat1$Y - mu1_hat)) -
  1/(1 - ps_hat) * ((1 - dat1$T) * (dat1$Y - mu0_hat))
psi_dr <- mu1_hat - mu0_hat + augmentedTerm

#Fit a random forest to the pseudo-outcome
tau_dr_fit <- ranger(y = psi_dr, x = dat1[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)

#Compute the CATE as the predictions from the pseudo-outcome regression
cate_dr <- tau_dr_fit$predictions 
dat1$CATE<-cate_dr
dat1$statin <- factor(dat1$statin)
 #Create the plot
fig_DRranger<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) +  
  theme_minimal() +  
  labs(x = "eGFR", y = "CATE", title = "") 
ggsave(filename = file.path(output_dir, paste0("fig_DRranger_", suffix, ".png")), fig_DRranger)

##5-5. R-learner
dat1<-dat0
#Train a regression model for m(X) = E(Y|X) and obtain predictions
m_fit <- ranger(y = dat1$Y, x = dat1[, covariates], keep.inbag = TRUE, seed = setseed, num.threads =nthread)
m_hat <- m_fit$predictions 

#Compute the pseudo-outcome of the R-learner
resid_treat <- dat1$T - ps_hat
resid_out <- dat1$Y - m_hat
psi_r <- resid_out / resid_treat

#Compute weights
w <- resid_treat ^ 2

#Regress pseudo-outcome on covariates using weights w
tau_r_fit <- ranger(y = psi_r, x = dat1[, covariates], case.weights = w, keep.inbag = TRUE, seed = setseed, num.threads =nthread)

#Compute the CATE as the predictions from the weighted pseudo-outcome regression
cate_r <- tau_r_fit$predictions 
dat1$CATE<-cate_r
dat1$statin <- factor(dat1$statin)
#Create the plot
fig_Rranger<- ggplot(dat1, aes(x = eGFR, y = CATE, color = statin)) +
  geom_point() +  
  scale_color_manual(values = c(rgb(0,0,1,1/4), rgb(1,0,0,1/4))) + 
  theme_minimal() +  
  labs(x = "eGFR", y = "CATE", title = "")  
ggsave(filename = file.path(output_dir, paste0("fig_Rranger_", suffix, ".png")), fig_Rranger)

fig_meta<- grid.arrange(fig_Sranger+ ggtitle('S learner'), 
                       fig_Tranger+ ggtitle('T learner'), 
                       fig_Xranger+ ggtitle('X learner'), 
                       fig_DRranger+ ggtitle('DR learner'), 
                       fig_Rranger+ ggtitle('R learner'), 
                       ncol=2)
ggsave(filename = file.path(output_dir, paste0("metalearner_", suffix, ".png")), fig_meta)

return(list(Slearner = fig_Sranger))
return(list(Tlearner = fig_Tranger))
return(list(Xlearner = fig_Xranger))
return(list(DRlearner = fig_DRranger))
return(list(Rlearner = fig_Rranger))
return(list(mAll = fig_meta))
}

#Run the function for each dataset
dataset_names <- c("data_1", "data_2", "data_3", "data_4")
metaplots_list <- list()  # Initialize an empty list to store plots

#Loop through dataset names and call the analysis function
for (dataset_name in dataset_names) {
  #Retrieve the dataset
  dataset <- get(dataset_name)
  #Extract the numeric suffix
  suffix <- gsub("data_", "", dataset_name)
  #Call the analysis function
  plots <- run_step5(dataset, suffix)
  #Assign each plot a name with the suffix and store in the list
  for (plot_name in names(plots)) {
    full_plot_name <- paste(plot_name, suffix, sep = "_")
    metaplots_list[[full_plot_name]] <- plots[[plot_name]]
  }
}
```


```{r}
###Step 6: Evaluation of the model performance (example code for calibration)
##Cross-fitting can be found in the following link
##https://github.com/Koinoue/GRF-calibration/blob/main/AJEsimulation.r
dat1<-data_1
dat1 <- dat1 %>%
  mutate_at(vars(statin), ~ as.numeric(as.character(.)))
Y <-  (dat1$Y)
W <-  (dat1$T)
X0 <-  subset(dat1, select=-Y)
X1 <-  subset(X0, select=-T)
model_grf <- causal_forest(X1, Y, W, 
                           honesty = TRUE, 
                           tune.parameters="all",
                           seed = setseed,
                           num.threads = nthread)
hte_grf <- predict(model_grf)$predictions

dat1$CATE<-hte_grf
dat2<-data_1
tau.hat <- hte_grf #this is an example of causal forest but you can change to other algorithm to estimate tau.hat
num.rankings<-5

#Rank observations *within each fold* into quintiles according to their CATE predictions.
ranking <- rep(NA, N)
tau.hat.quantiles <- quantile(tau.hat, probs = seq(0, 1, by=1/num.rankings))
ranking<- cut(tau.hat, tau.hat.quantiles, include.lowest=TRUE,labels=seq(num.rankings))

#Average difference-in-means within each ranking (Valid only in randomized settings)
treatment <- "W"
outcome <- "Y"
fmla <- paste0(outcome, " ~ 0 + ranking + ranking:", treatment)
ols.ate <- lm(fmla, data=transform(dat2, ranking=factor(ranking)))
ols.ate <- coeftest(ols.ate, vcov=vcovHC(ols.ate, type='HC2'))
interact <- which(grepl(":", rownames(ols.ate)))
ols.ate <- data.frame("OLS", paste0("Q", seq(num.rankings)), ols.ate[interact, 1:2])
rownames(ols.ate) <- NULL 
colnames(ols.ate) <- c("method", "ranking", "estimate", "std.err")
ols.ate

#Computing AIPW scores.
e.hat <- model_grf$W.hat # P[W=1|X]
m.hat <- model_grf$Y.hat # E[Y|X]

#Estimating mu.hat(X, 1) and mu.hat(X, 0) for obs in held-out sample
#https://grf-labs.github.io/grf/articles/muhats.html
mu.hat.0 <- m.hat - e.hat * tau.hat        # E[Y|X,W=0] = E[Y|X] - e(X)*tau(X)
mu.hat.1 <- m.hat + (1 - e.hat) * tau.hat  # E[Y|X,W=1] = E[Y|X] + (1 - e(X))*tau(X)

#AIPW scores
aipw.scores <- tau.hat + W / e.hat * (Y -  mu.hat.1) - (1 - W) / (1 - e.hat) * (Y -  mu.hat.0)
ols <- lm(aipw.scores ~ 0 + factor(ranking))
forest.ate <- data.frame("AIPW", paste0("Q", seq(num.rankings)), coeftest(ols, vcov=vcovHC(ols, "HC2"))[,1:2])
colnames(forest.ate) <- c("method", "ranking", "estimate", "std.err")
rownames(forest.ate) <- NULL 
forest.ate

#Concatenate the two results.
res <- rbind(forest.ate, ols.ate)

#Create the plot
res %>%
  as.data.frame() %>% 
  ggplot(aes(x = ranking, y = estimate, group=method, color=method)) +
  geom_point(position=position_dodge(0.3), size = 3) +
  geom_errorbar(aes(ymin=estimate-2*std.err, ymax=estimate+2*std.err), width=.2, position=position_dodge(0.3)) +
  ylab("") + xlab("") +
  theme_minimal() +
  theme(legend.position="bottom", legend.title = element_blank(), legend.text = element_text(size = 14, color = "black"),
        text = element_text(size = 14, color = "black"),
        axis.text = element_text(size = 14, color = "black")) +
  xlab("CATE ranking") +
  ylab("Estimated group-specific ATE")
```   

```{r}
Sys.time()
```
